// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220316212217_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.MakeAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TourTimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TourTimeId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Email = "blah@blah.com",
                            GroupName = "test",
                            GroupSize = 4,
                            Phone = "555-555-5555",
                            TourTimeId = 1
                        });
                });

            modelBuilder.Entity("Mission12.Models.TourTime", b =>
                {
                    b.Property<int>("TourTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TourTimeId");

                    b.ToTable("tourtimes");

                    b.HasData(
                        new
                        {
                            TourTimeId = 1,
                            Time = "Monday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 2,
                            Time = "Monday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 3,
                            Time = "Monday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 4,
                            Time = "Monday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 5,
                            Time = "Monday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 6,
                            Time = "Monday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 7,
                            Time = "Monday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 8,
                            Time = "Monday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 9,
                            Time = "Monday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 10,
                            Time = "Monday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 11,
                            Time = "Monday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 12,
                            Time = "Monday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 13,
                            Time = "Monday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 14,
                            Time = "Tuesday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 15,
                            Time = "Tuesday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 16,
                            Time = "Tuesday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 17,
                            Time = "Tuesday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 18,
                            Time = "Tuesday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 19,
                            Time = "Tuesday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 20,
                            Time = "Tuesday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 21,
                            Time = "Tuesday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 22,
                            Time = "Tuesday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 23,
                            Time = "Tuesday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 24,
                            Time = "Tuesday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 25,
                            Time = "Tuesday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 26,
                            Time = "Tuesday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 27,
                            Time = "Wednesday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 28,
                            Time = "Wednesday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 29,
                            Time = "Wednesday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 30,
                            Time = "Wednesday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 31,
                            Time = "Wednesday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 32,
                            Time = "Wednesday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 33,
                            Time = "Wednesday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 34,
                            Time = "Wednesday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 35,
                            Time = "Wednesday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 36,
                            Time = "Wednesday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 37,
                            Time = "Wednesday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 38,
                            Time = "Wednesday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 39,
                            Time = "Wednesday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 40,
                            Time = "Thursday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 41,
                            Time = "Thursday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 42,
                            Time = "Thursday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 43,
                            Time = "Thursday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 44,
                            Time = "Thursday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 45,
                            Time = "Thursday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 46,
                            Time = "Thursday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 47,
                            Time = "Thursday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 48,
                            Time = "Thursday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 49,
                            Time = "Thursday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 50,
                            Time = "Thursday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 51,
                            Time = "Thursday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 52,
                            Time = "Thursday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 53,
                            Time = "Friday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 54,
                            Time = "Friday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 55,
                            Time = "Friday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 56,
                            Time = "Friday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 57,
                            Time = "Friday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 58,
                            Time = "Friday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 59,
                            Time = "Friday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 60,
                            Time = "Friday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 61,
                            Time = "Friday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 62,
                            Time = "Friday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 63,
                            Time = "Friday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 64,
                            Time = "Friday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 65,
                            Time = "Friday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 66,
                            Time = "Saturday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 67,
                            Time = "Saturday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 68,
                            Time = "Saturday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 69,
                            Time = "Saturday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 70,
                            Time = "Saturday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 71,
                            Time = "Saturday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 72,
                            Time = "Saturday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 73,
                            Time = "Saturday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 74,
                            Time = "Saturday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 75,
                            Time = "Saturday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 76,
                            Time = "Saturday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 77,
                            Time = "Saturday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 78,
                            Time = "Saturday 8:00 PM"
                        },
                        new
                        {
                            TourTimeId = 79,
                            Time = "Sunday 8:00 AM"
                        },
                        new
                        {
                            TourTimeId = 80,
                            Time = "Sunday 9:00 AM"
                        },
                        new
                        {
                            TourTimeId = 81,
                            Time = "Sunday 10:00 AM"
                        },
                        new
                        {
                            TourTimeId = 82,
                            Time = "Sunday 11:00 AM"
                        },
                        new
                        {
                            TourTimeId = 83,
                            Time = "Sunday 12:00 PM"
                        },
                        new
                        {
                            TourTimeId = 84,
                            Time = "Sunday 1:00 PM"
                        },
                        new
                        {
                            TourTimeId = 85,
                            Time = "Sunday 2:00 PM"
                        },
                        new
                        {
                            TourTimeId = 86,
                            Time = "Sunday 3:00 PM"
                        },
                        new
                        {
                            TourTimeId = 87,
                            Time = "Sunday 4:00 PM"
                        },
                        new
                        {
                            TourTimeId = 88,
                            Time = "Sunday 5:00 PM"
                        },
                        new
                        {
                            TourTimeId = 89,
                            Time = "Sunday 6:00 PM"
                        },
                        new
                        {
                            TourTimeId = 90,
                            Time = "Sunday 7:00 PM"
                        },
                        new
                        {
                            TourTimeId = 91,
                            Time = "Sunday 8:00 PM"
                        });
                });

            modelBuilder.Entity("Mission12.Models.MakeAppointment", b =>
                {
                    b.HasOne("Mission12.Models.TourTime", "TourTime")
                        .WithMany()
                        .HasForeignKey("TourTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
